apiVersion: "recommender.com/v1"
kind: Autotune
metadata:
  name: "petclinic-autotune-max-http-throughput"
  namespace: "default"
spec:
  slo:
    objective_function:
      function_type: "expression"
      expression: "request_count"
    slo_class: "throughput"
    direction: "maximize"
    function_variables:
    - name: "request_count"
      query: rate(http_server_requests_seconds_count{exception="None",method="GET",outcome="SUCCESS",status="200",uri="/webjars/**",}[1m])
      datasource: "prometheus"
      value_type: "double"
  mode: "experiment"
  selector:
    matchLabel: "app.kubernetes.io/name"
    matchLabelValue: "petclinic-deployment"
    matchRoute: ""
    matchURI: ""
    matchService: ""
