apiVersion: "recommender.com/v1"
kind: Autotune
metadata:
  name: "galaxies-autotune-max-app-throughput"
  namespace: "default"
spec:
  slo:
    objective_function:
      function_type: "expression"
      expression: "app_getop_count"
    slo_class: "throughput"
    direction: "maximize"
    function_variables:
    - name: "app_getop_count"
      query: getop_timer_seconds_count{class="org.restcrud.Galaxies",exception="none",method="get",}
      datasource: "prometheus"
      value_type: "double"
  mode: "experiment"
  selector:
    matchLabel: "app.kubernetes.io/name"
    matchLabelValue: "galaxies-deployment"
    matchRoute: ""
    matchURI: ""
    matchService: ""
