apiVersion: "recommender.com/v1"
kind: Autotune
metadata:
  name: "quarkus-resteasy-autotune-min-http-response-time-db"
  namespace: "default"
spec:
  slo:
    objective_function:
      function_type: "expression"
      expression: "(1.25 * request_count) - (1.5 * (request_sum / request_count)) - (0.25 * request_max)"
    slo_class: "response_time"
    direction: "minimize"
    function_variables:
    - name: "request_sum"
      query: rate(http_server_requests_seconds_sum{method="GET",outcome="SUCCESS",status="200",uri="/db",}[1m])
      datasource: "prometheus"
      value_type: "double"
    - name: "request_count"
      query: rate(http_server_requests_seconds_count{method="GET",outcome="SUCCESS",status="200",uri="/db",}[1m])
      datasource: "prometheus"
      value_type: "double"
    - name: "request_max"
      query: http_server_requests_seconds_max{method="GET",outcome="SUCCESS",status="200",uri="/db"}
      datasource: "prometheus"
      value_type: "double"

  mode: "experiment"
  selector:
    matchLabel: "app.kubernetes.io/name"
    matchLabelValue: "tfb-qrh-deployment"
    matchRoute: ""
    matchURI: ""
    matchService: ""
